name: Test
on:
  push:
    branches: [master]
    tags: [ v* ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: coursier/cache-action@v6
      - uses: olafurpg/setup-scala@v12

      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - uses: actions/cache@v2
        name: Cache node_modules
        with:
          path: "**/main/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/main/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - uses: actions/cache@v2
        name: Cache scala targets
        with:
          path: "**/target"
          key: ${{ runner.os }}-scala-target-${{ github.sha }}

      - run: ./publish.sh
      - run: cd npm/

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      # - name: Debug over SSH (tmate)
      #   # if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true
